### PR TITLE
Updated to handle client_max_window_bits default values, required by some browsers.

### PR DESCRIPTION
**Pull request by MFernstrom**

### CODE REVIEW

**Comment by MFernstrom** [comment]
Not a clue why GitHub diff is so insane, I only modified the CreateServerConnection function.

**Comment by MFernstrom** [comment]
@Robert-112 You maintaining this repo? Or is it a ghost project?

**Comment by Robert-112** [comment]
Hallo MFernstorm,

I downloaded this code from a Google-Code Project:
https://code.google.com/archive/p/bauglir-websocket/
 
Later i used the Code with Lazarus 1.6 .
Now i switched total node.js and Socket.io

Best regards
Robert

**Comment by MFernstrom** [comment]
Allright, I'll drop the PR.

**Pull request closed without merging**
